website-skeleton/src/Entity/Streaming.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StreamingRepository")
 */
class Streaming
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre_morceau;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $qualite;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Client", inversedBy="client_streaming")
     */
    private $streaming_produit;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Produit", inversedBy="streamings")
     */
    private $streamingxproduit;

    public function __construct()
    {
        $this->streaming_produit = new ArrayCollection();
        $this->streamingxproduit = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getTitreMorceau(): ?string
    {
        return $this->titre_morceau;
    }

    public function setTitreMorceau(string $titre_morceau): self
    {
        $this->titre_morceau = $titre_morceau;

        return $this;
    }

    public function getQualite(): ?string
    {
        return $this->qualite;
    }

    public function setQualite(string $qualite): self
    {
        $this->qualite = $qualite;

        return $this;
    }

    /**
     * @return Collection|Client[]
     */
    public function getStreamingProduit(): Collection
    {
        return $this->streaming_produit;
    }

    public function addStreamingProduit(Client $streamingProduit): self
    {
        if (!$this->streaming_produit->contains($streamingProduit)) {
            $this->streaming_produit[] = $streamingProduit;
        }

        return $this;
    }

    public function removeStreamingProduit(Client $streamingProduit): self
    {
        if ($this->streaming_produit->contains($streamingProduit)) {
            $this->streaming_produit->removeElement($streamingProduit);
        }

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getStreamingxproduit(): Collection
    {
        return $this->streamingxproduit;
    }

    public function addStreamingxproduit(Produit $streamingxproduit): self
    {
        if (!$this->streamingxproduit->contains($streamingxproduit)) {
            $this->streamingxproduit[] = $streamingxproduit;
        }

        return $this;
    }

    public function removeStreamingxproduit(Produit $streamingxproduit): self
    {
        if ($this->streamingxproduit->contains($streamingxproduit)) {
            $this->streamingxproduit->removeElement($streamingxproduit);
        }

        return $this;
    }
}

website-skeleton/src/Form/StreamingType.php
<?php

namespace App\Form;

use App\Entity\Streaming;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StreamingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('prix')
            ->add('titre_morceau')
            ->add('qualite')
            ->add('streaming_produit')
            ->add('streamingxproduit')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Streaming::class,
        ]);
    }
}

website-skeleton/src/Controller/StreamingController.php
<?php

namespace App\Controller;

use App\Entity\Streaming;
use App\Form\StreamingType;
use App\Repository\StreamingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/streaming")
 */
class StreamingController extends AbstractController
{
    /**
     * @Route("/", name="streaming_index", methods={"GET"})
     */
    public function index(StreamingRepository $streamingRepository): Response
    {
        return $this->render('streaming/index.html.twig', [
            'streamings' => $streamingRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="streaming_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $streaming = new Streaming();
        $form = $this->createForm(StreamingType::class, $streaming);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($streaming);
            $entityManager->flush();

            return $this->redirectToRoute('streaming_index');
        }

        return $this->render('streaming/new.html.twig', [
            'streaming' => $streaming,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="streaming_show", methods={"GET"})
     */
    public function show(Streaming $streaming): Response
    {
        return $this->render('streaming/show.html.twig', [
            'streaming' => $streaming,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="streaming_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Streaming $streaming): Response
    {
        $form = $this->createForm(StreamingType::class, $streaming);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('streaming_index');
        }

        return $this->render('streaming/edit.html.twig', [
            'streaming' => $streaming,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="streaming_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Streaming $streaming): Response
    {
        if ($this->isCsrfTokenValid('delete'.$streaming->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($streaming);
            $entityManager->flush();
        }

        return $this->redirectToRoute('streaming_index');
    }
}

website-skeleton/templates/streaming/_delete_form.html.twig
<form method="post" action="{{ path('streaming_delete', {'id': streaming.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ streaming.id) }}">
    <button class="btn">Delete</button>
</form>

website-skeleton/templates/streaming/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

website-skeleton/templates/streaming/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Streaming{% endblock %}

{% block body %}
    <h1>Edit Streaming</h1>

    {{ include('streaming/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('streaming_index') }}">back to list</a>

    {{ include('streaming/_delete_form.html.twig') }}
{% endblock %}

website-skeleton/templates/streaming/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Streaming index{% endblock %}

{% block body %}
    <h1>Streaming index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Prix</th>
                <th>Titre_morceau</th>
                <th>Qualite</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for streaming in streamings %}
            <tr>
                <td>{{ streaming.id }}</td>
                <td>{{ streaming.prix }}</td>
                <td>{{ streaming.titreMorceau }}</td>
                <td>{{ streaming.qualite }}</td>
                <td>
                    <a href="{{ path('streaming_show', {'id': streaming.id}) }}">show</a>
                    <a href="{{ path('streaming_edit', {'id': streaming.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('streaming_new') }}">Create new</a>
{% endblock %}

website-skeleton/templates/streaming/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Streaming{% endblock %}

{% block body %}
    <h1>Create new Streaming</h1>

    {{ include('streaming/_form.html.twig') }}

    <a href="{{ path('streaming_index') }}">back to list</a>
{% endblock %}

website-skeleton/templates/streaming/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Streaming{% endblock %}

{% block body %}
    <h1>Streaming</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ streaming.id }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ streaming.prix }}</td>
            </tr>
            <tr>
                <th>Titre_morceau</th>
                <td>{{ streaming.titreMorceau }}</td>
            </tr>
            <tr>
                <th>Qualite</th>
                <td>{{ streaming.qualite }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('streaming_index') }}">back to list</a>

    <a href="{{ path('streaming_edit', {'id': streaming.id}) }}">edit</a>

    {{ include('streaming/_delete_form.html.twig') }}
{% endblock %}